### PR TITLE
Encode: check for errors while setting claim fields

### LINKED ISSUE #90: Missing error handling when set claim fields
```
func (ja *JWTAuth) Encode(claims map[string]interface{}) (t jwt.Token, tokenString string, err error) {
	t = jwt.New()
	for k, v := range claims {
		t.Set(k, v)
	}
	payload, err := ja.sign(t)
	if err != nil {
		return nil, "", err
	}
	tokenString = string(payload)
	return
}
```

If t.Set(k,v) returns error, we should handle it and error out earlier, instead of now just ignore it ? 
Look at the API t.Set(k, v), depending on the key's name, it may fail if we provide a wrong type for that key, e.g. the `sub` has to be string.

### PR DESCRIPTION
**Pull request by drakkan**
Fixes #90

### CODE REVIEW

File: jwtauth_test.go [hunk 1]
```diff
@@ -279,6 +279,23 @@ func TestMore(t *testing.T) {
...
+	claims := map[string]interface{}{
+		"key1": "val1",
+		"key2": 2,
+		"key3": time.Now(),
+		"key4": []string{"1", "2"},
+	}
+	claims[jwt.JwtIDKey] = 1
+	if _, _, err := TokenAuthHS256.Encode(claims); err == nil {
+		t.Fatal("encoding invalid claims succeeded")
+	}
```
Comment (VojtechVitek) [inline jwtauth_test.go:292]: This now fails correctly per RFC-7519:

```
The "jti" value is a case-
   sensitive string.  Use of this claim is OPTIONAL.
```

https://datatracker.ietf.org/doc/html/rfc7519#page-10

**Review by VojtechVitek — APPROVED** [review]
LGTM 👍 

Thank you!
